language: perl
perl:
  - "5.16"
  - "5.10"
before_install:
    - "cpanm -n Devel::Cover::Report::Coveralls"
    - "cpanm Module::Build::Pluggable Module::Build::Pluggable::CPANfile"

      
script:
  perl Build.PL && ./Build build && cover -test -report coveralls